
-- Run this entire script in Supabase Dashboard → SQL Editor.
-- The app uses the server-side service-role key, so these tables can stay protected.

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  name text unique not null,
  active boolean not null default true
);

create table if not exists public.meals (
  meal_date date not null,
  member text not null,
  meals numeric not null default 0,
  primary key (meal_date, member)
);

create table if not exists public.bazar (
  bazar_date date primary key,
  amount numeric not null default 0
);

create table if not exists public.deposits (
  member text primary key,
  amount numeric not null default 0
);

insert into public.members (name) values
('Omar'), ('JAHID'), ('Ovi'), ('Sarat')
on conflict (name) do nothing;
